### ISSUE TITLE
Entity states not updating properly

### ISSUE THREAD

**Issue by MasterDevwi** [weswitt/everlights3#2] opened 2023-11-27 06:05 UTC
Thanks so much for building this integration! It's exactly what I've been hoping for. After playing with it for a bit, I've noticed two bugs:

1) The entities in HA can control the Everlights properly, but the entity on/off state doesn't update in HA when the Everlights are turned on or off via the Everlights app.

2) The UI always says my lights are on the first effect, even if they're actually on a different one. Updating the effect via the UI works properly, but if I close the entity card and then reopen it the effect shown in the UI returns to the first item in the list (in my case, 4th of July).

![image](https://github.com/weswitt/everlights3/assets/5544757/5a69a624-100e-4f55-8edb-e67e856a05b2)

**Comment by weswitt** [comment] 2023-11-27 16:40
1) i think i know why this is happening and will try to fix it.

2) this seems to be a bug in ha. i posted about it here in the forums but no one has responded. the problem is that ha is never calling the effect property on my integration so the current effect is not correct. not sure there is anything i can do about it.

**Comment by weswitt** [comment] 2023-11-27 17:42
issue #1 fixed with commit: https://github.com/weswitt/everlights3/commit/7dc9b91c8fb0d8aef3aacf12f486137dc24004b6

issue #2 cannot be fixed as this is an ha bug

**Closed as completed by weswitt** 2023-11-27 17:42 UTC

**Comment by MasterDevwi** [comment] 2023-11-27 18:49
Awesome, thanks so much! No worries about #2, it's a much more minor issue. As long as I can set it properly and it doesn't get reset on its own I'm not worried if it's not showing the correct state yet. Although hopefully that can be fixed eventually too.

**Comment by MasterDevwi** [comment] 2023-11-27 18:58
@weswitt I may have spoken too soon. I installed the latest update and it's updating the state now (yay!), but it takes about 30 seconds to update. The delay on its own isn't too bad, but I've noticed that if I toggle the light on in HA the toggle immediately switches from on to off, waits about 30 seconds, and then switches back on. The opposite happens when I turn it off (the toggle turns back on, waits about 30 seconds, and then reverts to the correct off state).

**Comment by weswitt** [comment] 2023-11-27 19:02
yea, i believe the delay is the everlights hardware.  the #2 issue is very annoying and i really wish i could fix it.

**Comment by weswitt** [comment] 2023-11-27 19:15
i see what you are seeing, but i added some logging to the update method. i can see that when update is called i query everlights for the status and it reports that the light is off even though it is on. eventually it does return true that the light is on. very strange.

**Comment by MasterDevwi** [comment] 2023-11-27 19:18
I wonder if the code should just wait a little while (30 seconds?) after calling update and before querying Everlights to give Everlights time to properly update the status on its end? I guess that would mean that if something failed the toggle wouldn't turn off until after the timer expires, but that may be acceptable to ensure it works well in the general case?

**Comment by weswitt** [comment] 2023-11-27 19:20
it's 100% the everlights hardware / firmware. i ran a test where i turn on the lights via the everlights app. then i query the everlights api using curl. the lights are on but the api returns false for the zone status for a while and the eventually it returns true. this is a bug in the everlights api.

**Comment by MasterDevwi** [comment] 2023-11-27 20:57
Gotcha. At least we know where the issue is. Do you think a delay might make sense before querying Everlights for the state so the toggle doesn't erroneously switch off and then back on?
